### PR TITLE
mspm0: CmakeLists: link dl_timer.c

### PR DESCRIPTION
**Pull request by dkarnikis**
Needed to use hardware clocks/timers

### CODE REVIEW

**Review by hansbinderup — APPROVED** [review]
Title is incorrect; you're both compiling and linking the `dl_timer.c` source :)

**Comment by dkarnikis** [comment]
@hansbinderup you are right, i will fix that. btw am i rebasing against the correct branch?

**Comment by hansbinderup** [comment]
> @hansbinderup you are right, i will fix that. btw am i rebasing against the correct branch?

The target branch should be [this instead](https://github.com/AudioStreamingPlatform/hal_ti/tree/ti/mspm0_upstream) :)

**Comment by dkarnikis** [comment]
will close this one and rebase against the correct one then!

**Pull request closed without merging**
